version: '3'
services:
  server:
    image: cuongnb14/logio:0.1.0
    ports:
      - '28778:28778'
      - '28777:28777'
    volumes:
      - ../log.io-conf/:/root/.log.io/
    command: log.io-server
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"