version: '3'
services:
  harvester:
    image: cuongnb14/logio:0.1.0
    user: root
    volumes:
      - ../log.io-conf/:/root/.log.io/
      - '/var/log/apache2/error.log:/logs'
    command: log.io-harvester
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"